import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ko' | 'en' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'ecoapp_language';

const translations = {
  ko: {
    // Common
    'common.points': '포인트',
    'common.kg': 'kg',
    'common.confirm': '확인',
    'common.cancel': '취소',
    'common.close': '닫기',
    'common.search': '검색',
    'common.all': '전체',
    
    // Bottom Nav
    'nav.home': '홈',
    'nav.camera': '카메라',
    'nav.search': '검색',
    'nav.ranking': '랭킹',
    'nav.rewards': '리워드',
    'nav.map': '지도',
    
    // Dashboard
    'dashboard.greeting': '안녕하세요!',
    'dashboard.username': '에코 워리어님 🌱',
    'dashboard.myPoints': '보유 포인트',
    'dashboard.monthlyTotal': '이번 달 총량',
    'dashboard.goalProgress': '이번 달 목표 달성률',
    'dashboard.current': '현재',
    'dashboard.goal': '목표',
    'dashboard.weeklyTrend': '7일간 분리수거',
    'dashboard.thisWeek': '이번 주',
    'dashboard.lastWeek': '지난 주',
    'dashboard.recycled': '재활용',
    'dashboard.chartDescription': '7일간 분리수거한 양을 보여줍니다',
    'dashboard.cameraRecognition': '카메라 인식',
    'dashboard.startRecycling': '분리수거 시작',
    'dashboard.searchByName': '이름으로 검색',
    'dashboard.findItems': '품목 찾기',
    'dashboard.dailyTip': '💡 오늘의 환경 팁',
    'dashboard.recentActivity': '최근 활동',
    'dashboard.tip1': '🌍 플라스틱 1kg 재활용으로 CO₂ 2.3kg 절감!',
    'dashboard.tip2': '♻️ 캔을 분리수거하면 95%의 에너지 절약!',
    'dashboard.tip3': '💚 오늘도 지구를 위한 한 걸음, 최고예요!',
    
    // Camera
    'camera.title': 'AI 분리수거 인식',
    'camera.instruction': '분리수거 품목을 화면 중앙에\n위치시켜주세요',
    'camera.result': '분류 결과',
    'camera.category.recycle': '재활용',
    'camera.category.organic': '유기물',
    'camera.category.hazardous': '유해',
    'camera.category.other': '기타',
    'camera.accuracy': '정확도',
    'camera.expectedPoints': '예상 포인트',
    'camera.co2Reduction': 'CO₂ 절감',
    'camera.howTo': '올바른 처리 방법',
    'camera.complete': '처리 완료',
    'camera.weightInput': '무게 입력',
    'camera.enterWeight': '분리수거한 무게를 입력해주세요',
    'camera.earnPoints': '적립하기',
    'camera.success': '포인트 적립 완료!',
    'camera.greatChoice': '지구를 위한 멋진 선택이에요!',
    'camera.loadingCamera': '카메라 시작 중...',
    'camera.takePhoto': '사진을 찍어 분석하세요',
    'camera.pressBelow': '아래 버튼을 눌러 카메라를 열어주세요',
    'camera.placeItem': '물품을 프레임 안에 위치시켜주세요',
    'camera.analyzing': 'AI로 분석 중...',
    'camera.pointsEarned': '적립 포인트',
    'camera.co2Saved': 'CO₂ 절감',
    'camera.errorAnalysis': '분석 실패',
    'camera.tryAgain': '다시 시도',
    'camera.tryAgainDesc': '다른 사진을 찍거나 네트워크 연결을 확인하세요',
    'camera.cannotConnect': 'AI에 연결할 수 없습니다. 다시 시도해주세요.',
    'camera.unknown': '알 수 없음',
    
    // Encyclopedia
    'encyclopedia.title': '분리수거 백과사전',
    'encyclopedia.searchPlaceholder': '품목 이름을 검색하세요',
    'encyclopedia.category.recycle': '재활용',
    'encyclopedia.category.organic': '유기물',
    'encyclopedia.category.hazardous': '유해',
    'encyclopedia.category.other': '기타',
    'encyclopedia.noResults': '검색 결과가 없습니다',
    'encyclopedia.detail': '품목 상세 정보',
    'encyclopedia.disposalLocation': '배출 장소',
    'encyclopedia.classificationReason': '분류 이유',
    'encyclopedia.environmentalBenefit': '🌍 환경적 이점',
    'encyclopedia.processingMethod': '처리 방법',
    
    // Ranking
    'ranking.title': '리더보드',
    'ranking.individual': '개인',
    'ranking.class': '학급',
    'ranking.neighborhood': '동네',
    'ranking.weekly': '주간',
    'ranking.monthly': '월간',
    'ranking.you': '당신',
    'ranking.members': '명',
    'ranking.badges': '내 배지 컬렉션',
    'ranking.yourRank': '나의 순위',
    'ranking.points': '포인트',
    'ranking.streak': '연속',
    'ranking.viewMyPosition': '내 위치 보기',
    'ranking.vsLastWeek': '지난 주 대비',
    'ranking.badge.streak7': '7일 연속 참여',
    'ranking.badge.kg100': '100kg 달성',
    'ranking.badge.master': '에코 마스터',
    'ranking.badge.points1000': '1000포인트',
    'ranking.badge.streak30': '30일 연속 참여',
    'ranking.allTime': '전체',
    'ranking.badge.description.streak7': '7일 연속 분리수거',
    'ranking.badge.description.kg100': '총 100kg 분리수거 달성',
    'ranking.badge.description.master': '에코 마스터 레벨 달성',
    'ranking.badge.description.points1000': '1000 포인트 적립',
    'ranking.badge.description.streak30': '30일 연속 분리수거',
    'ranking.badge.condition.streak7': '연속 >= 7일',
    'ranking.badge.condition.kg100': '총 kg >= 100',
    'ranking.badge.condition.master': '50회 분리수거 완료',
    'ranking.badge.condition.points1000': '포인트 >= 1000',
    'ranking.badge.condition.streak30': '연속 >= 30일',
    'ranking.progress': '진행률',
    'ranking.unlocked': '획득',
    'ranking.locked': '잠금',
    'ranking.badgeDetail': '배지 상세 정보',
    
    // Rewards Extended
    'rewards.featured': '추천 상품',
    'rewards.hot': 'HOT',
    'rewards.pointsNeeded': '필요',
    'rewards.default': '기본',
    'rewards.priceLow': '낮은 가격',
    'rewards.priceHigh': '높은 가격',
    'rewards.showQR': 'QR 코드 표시',
    'rewards.couponCode': '쿠폰 코드',
    'rewards.expiresIn': '만료까지',
    'rewards.days': '일',
    'rewards.expired': '만료됨',
    'rewards.expiringSoon': '곧 만료',
    'rewards.noHistory': '내역이 없습니다',
    'rewards.nextReward': '다음 보상까지',
    'rewards.progressToNext': '다음 보상까지 진행률',
    
    // Map Extended
    'map.searchPlaceholder': '장소, 재료 검색...',
    'map.updateLocation': '위치 업데이트',
    'map.sortBy': '정렬',
    'map.sortDistance': '가까운 순',
    'map.sortName': '이름순',
    'map.favorites': '즐겨찾기',
    'map.noResults': '검색 결과 없음',
    'map.clearFilter': '필터 해제',
    'map.points': '개 지점',
    'map.events': '개 이벤트',
    'map.participants': '참여자',
    'map.registered': '등록됨',
    'map.register': '참여하기',
    'map.full': '마감',
    'map.cancelRegistration': '등록 취소됨',
    'map.registerSuccess': '등록 성공!',
    'map.share': '공유하기',
    'map.linkCopied': '링크 복사됨!',
    'map.favorite': '즐겨찾기',
    'map.coordinates': '좌표',
    'map.shareLocation': '위치 공유',
    'map.gpsError.denied': '위치 접근이 거부되었습니다',
    'map.gpsError.unavailable': '위치를 확인할 수 없습니다',
    'map.gpsError.timeout': '시간 초과',
    'map.gpsError.unknown': '알 수 없는 오류',
    'map.gpsError.noSupport': '브라우저가 GPS를 지원하지 않습니다',
    
    // Encyclopedia Extended  
    'encyclopedia.aiSearch': 'AI 검색',
    'encyclopedia.searching': '검색 중...',
    'encyclopedia.searchHistory': '검색 기록',
    'encyclopedia.clearHistory': '기록 삭제',
    'encyclopedia.popularSearches': '인기 검색어',
    'encyclopedia.aiResult': 'AI 결과',
    'encyclopedia.searchError': '검색 실패. 다시 시도해주세요.',
    
    // Campaign  
    'campaign.title1': '달랏 환경 캠페인',
    'campaign.desc1': '플라스틱 제로 챌린지',
    'campaign.title2': '재활용 교육 프로그램',
    'campaign.desc2': '올바른 분류 방법',
    'campaign.title3': '뚜옌람 호수 청소',
    'campaign.desc3': '호수 주변 쓰레기 수거',
    
    // Rewards
    'rewards.title': '리워드 샵',
    'rewards.balance': '보유 포인트',
    'rewards.shop': '상점',
    'rewards.history': '포인트 내역',
    'rewards.myCoupons': '내 쿠폰함',
    'rewards.category.coupons': '쿠폰',
    'rewards.category.ecoGoods': '친환경 굿즈',
    'rewards.category.certificate': '전자 인증서',
    'rewards.stock': '재고',
    'rewards.exchange': '교환하기',
    'rewards.notEnoughPoints': '포인트 부족',
    'rewards.confirmExchange': '교환하시겠습니까?',
    'rewards.requiredPoints': '필요 포인트',
    'rewards.afterBalance': '교환 후 잔액',
    'rewards.earned': '적립',
    'rewards.used': '사용',
    'rewards.balance2': '잔액',
    'rewards.available': '사용가능',
    'rewards.usedComplete': '사용완료',
    'rewards.use': '사용하기',
    'rewards.noCoupons': '보유한 쿠폰이 없습니다',
    
    // Map
    'map.title': '수거 거점 지도',
    'map.findLocation': '내 위치 찾기',
    'map.nearbyBins': '내 주변 수거함',
    'map.campaigns': '지역 환경 캠페인',
    'map.detail': '수거함 상세 정보',
    'map.operatingHours': '운영 시간',
    'map.acceptedItems': '수거 가능 품목',
    'map.getDirections': '길 안내 시작',
    'map.type.recycle': '재활용',
    'map.type.battery': '폐건전지',
    'map.type.glass': '유리병',
    'map.type.general': '일반',
    
    // Items
    'item.plasticBottle': '플라스틱 생수병',
    'item.foodWaste': '음식물 쓰레기',
    'item.battery': '폐건전지',
    'item.paperCup': '종이컵',
    'item.styrofoam': '스티로폼',
    'item.plasticBag': '비닐봉지',
    
    // Locations (Dalat)
    'location.dalat1': '달랏 재활용 센터',
    'location.dalat2': '쑤언흐엉 폐건전지 수거함',
    'location.dalat3': '달랏종합수거센터',
    'location.dalat4': '유리병 전용 수거함',
    
    // Notifications
    'notifications.title': '알림',
    'notifications.1.title': '🎉 7일 연속 참여!',
    'notifications.1.message': '7일 연속 분리수거를 하셨습니다. 계속 파이팅!',
    'notifications.2.title': '🎁 새로운 리워드',
    'notifications.2.message': '4500 포인트로 Coffee Voucher를 교환할 수 있습니다',
    'notifications.3.title': '💡 오늘의 팁',
    'notifications.3.message': '플라스틱 병을 분리수거 통에 넣기 전에 씨어주세요',
  },
  
  en: {
    // Common
    'common.points': 'Points',
    'common.kg': 'kg',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.all': 'All',
    
    // Bottom Nav
    'nav.home': 'Home',
    'nav.camera': 'Camera',
    'nav.search': 'Search',
    'nav.ranking': 'Ranking',
    'nav.rewards': 'Rewards',
    'nav.map': 'Map',
    
    // Dashboard
    'dashboard.greeting': 'Hello!',
    'dashboard.username': 'Eco Warrior 🌱',
    'dashboard.myPoints': 'My Points',
    'dashboard.monthlyTotal': 'Monthly Total',
    'dashboard.goalProgress': 'Monthly Goal Progress',
    'dashboard.current': 'Current',
    'dashboard.goal': 'Goal',
    'dashboard.weeklyTrend': '7-Day Recycling',
    'dashboard.thisWeek': 'This week',
    'dashboard.lastWeek': 'Last week',
    'dashboard.recycled': 'Recycled',
    'dashboard.chartDescription': 'Shows your recycling over the past 7 days',
    'dashboard.cameraRecognition': 'Camera Recognition',
    'dashboard.startRecycling': 'Start Recycling',
    'dashboard.searchByName': 'Search by Name',
    'dashboard.findItems': 'Find Items',
    'dashboard.dailyTip': '💡 Daily Eco Tip',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.tip1': '🌍 Recycling 1kg of plastic reduces CO₂ by 2.3kg!',
    'dashboard.tip2': '♻️ Recycling cans saves 95% of energy!',
    'dashboard.tip3': '💚 Another great step for the planet!',
    
    // Camera
    'camera.title': 'AI Recycling Recognition',
    'camera.instruction': 'Place the recyclable item\nin the center of the screen',
    'camera.result': 'Classification Result',
    'camera.category.recycle': 'Recyclable',
    'camera.category.organic': 'Organic',
    'camera.category.hazardous': 'Hazardous',
    'camera.category.other': 'Other',
    'camera.accuracy': 'Accuracy',
    'camera.expectedPoints': 'Expected Points',
    'camera.co2Reduction': 'CO₂ Reduction',
    'camera.howTo': 'Proper Disposal Method',
    'camera.complete': 'Complete',
    'camera.weightInput': 'Enter Weight',
    'camera.enterWeight': 'Please enter the weight of recyclables',
    'camera.earnPoints': 'Earn Points',
    'camera.success': 'Points Earned!',
    'camera.greatChoice': 'Great choice for the planet!',
    'camera.loadingCamera': 'Starting camera...',
    'camera.takePhoto': 'Take a photo to analyze',
    'camera.pressBelow': 'Press the button below to open camera',
    'camera.placeItem': 'Place the item in the frame',
    'camera.analyzing': 'Analyzing with AI...',
    'camera.pointsEarned': 'Points Earned',
    'camera.co2Saved': 'CO₂ Saved',
    'camera.errorAnalysis': 'Analysis Error',
    'camera.tryAgain': 'Try Again',
    'camera.tryAgainDesc': 'Please take another photo or check network connection',
    'camera.cannotConnect': 'Cannot connect to AI. Please try again.',
    'camera.unknown': 'Unknown',
    
    // Encyclopedia
    'encyclopedia.title': 'Recycling Encyclopedia',
    'encyclopedia.searchPlaceholder': 'Search for items',
    'encyclopedia.category.recycle': 'Recyclable',
    'encyclopedia.category.organic': 'Organic',
    'encyclopedia.category.hazardous': 'Hazardous',
    'encyclopedia.category.other': 'Other',
    'encyclopedia.noResults': 'No results found',
    'encyclopedia.detail': 'Item Details',
    'encyclopedia.disposalLocation': 'Disposal Location',
    'encyclopedia.classificationReason': 'Classification Reason',
    'encyclopedia.environmentalBenefit': '🌍 Environmental Benefit',
    'encyclopedia.processingMethod': 'Processing Method',
    
    // Ranking
    'ranking.title': 'Leaderboard',
    'ranking.individual': 'Individual',
    'ranking.class': 'Class',
    'ranking.neighborhood': 'District',
    'ranking.weekly': 'Weekly',
    'ranking.monthly': 'Monthly',
    'ranking.you': 'You',
    'ranking.members': 'members',
    'ranking.badges': 'My Badge Collection',    'ranking.yourRank': 'Your Rank',
    'ranking.points': 'Points',
    'ranking.streak': 'Streak',
    'ranking.viewMyPosition': 'View my position',
    'ranking.vsLastWeek': 'vs last week',    'ranking.badge.streak7': '7-Day Streak',
    'ranking.badge.kg100': '100kg Achievement',
    'ranking.badge.master': 'Eco Master',
    'ranking.badge.points1000': '1000 Points',
    'ranking.badge.streak30': '30-Day Streak',
    'ranking.allTime': 'All Time',
    'ranking.badge.description.streak7': 'Recycle for 7 consecutive days',
    'ranking.badge.description.kg100': 'Recycle a total of 100kg',
    'ranking.badge.description.master': 'Reach Eco Master level',
    'ranking.badge.description.points1000': 'Earn 1000 reward points',
    'ranking.badge.description.streak30': 'Recycle for 30 consecutive days',
    'ranking.badge.condition.streak7': 'Streak >= 7 days',
    'ranking.badge.condition.kg100': 'Total kg >= 100',
    'ranking.badge.condition.master': 'Complete 50 recyclings',
    'ranking.badge.condition.points1000': 'Points >= 1000',
    'ranking.badge.condition.streak30': 'Streak >= 30 days',
    'ranking.progress': 'Progress',
    'ranking.unlocked': 'Unlocked',
    'ranking.locked': 'Locked',
    'ranking.badgeDetail': 'Badge Details',
    
    // Rewards Extended
    'rewards.featured': 'Featured Items',
    'rewards.hot': 'HOT',
    'rewards.pointsNeeded': 'Need',
    'rewards.default': 'Default',
    'rewards.priceLow': 'Price: Low',
    'rewards.priceHigh': 'Price: High',
    'rewards.showQR': 'Show QR Code',
    'rewards.couponCode': 'Coupon Code',
    'rewards.expiresIn': 'Expires in',
    'rewards.days': 'days',
    'rewards.expired': 'Expired',
    'rewards.expiringSoon': 'Expiring soon',
    'rewards.noHistory': 'No history yet',
    'rewards.nextReward': 'Next Reward',
    'rewards.progressToNext': 'Progress to next reward',
    
    // Map Extended
    'map.searchPlaceholder': 'Search locations, materials...',
    'map.updateLocation': 'Update Location',
    'map.sortBy': 'Sort by',
    'map.sortDistance': 'Nearest',
    'map.sortName': 'Name A-Z',
    'map.favorites': 'favorites',
    'map.noResults': 'No locations found',
    'map.clearFilter': 'Clear filter',
    'map.points': 'points',
    'map.events': 'events',
    'map.participants': 'participants',
    'map.registered': 'Registered',
    'map.register': 'Register',
    'map.full': 'Full',
    'map.cancelRegistration': 'Registration cancelled',
    'map.registerSuccess': 'Registration successful!',
    'map.share': 'Share',
    'map.linkCopied': 'Link copied!',
    'map.favorite': 'Favorite',
    'map.coordinates': 'Coordinates',
    'map.shareLocation': 'Share Location',
    'map.gpsError.denied': 'Location access denied',
    'map.gpsError.unavailable': 'Location unavailable',
    'map.gpsError.timeout': 'Request timeout',
    'map.gpsError.unknown': 'Unknown error',
    'map.gpsError.noSupport': 'Browser does not support GPS',
    
    // Encyclopedia Extended
    'encyclopedia.aiSearch': 'AI Search',
    'encyclopedia.searching': 'Searching...',
    'encyclopedia.searchHistory': 'Search History',
    'encyclopedia.clearHistory': 'Clear History',
    'encyclopedia.popularSearches': 'Popular Searches',
    'encyclopedia.aiResult': 'AI Result',
    'encyclopedia.searchError': 'Search failed. Please try again.',
    
    // Campaign
    'campaign.title1': 'Dalat Environment Campaign',
    'campaign.desc1': 'Plastic-Free Challenge',
    'campaign.title2': 'Recycling Education Program',
    'campaign.desc2': 'Proper sorting methods',
    'campaign.title3': 'Tuyen Lam Lake Cleanup',
    'campaign.desc3': 'Collect trash around the lake',
    
    // Rewards
    'rewards.title': 'Reward Shop',
    'rewards.balance': 'Point Balance',
    'rewards.shop': 'Shop',
    'rewards.history': 'Point History',
    'rewards.myCoupons': 'My Coupons',
    'rewards.category.coupons': 'Coupons',
    'rewards.category.ecoGoods': 'Eco Goods',
    'rewards.category.certificate': 'E-Certificate',
    'rewards.stock': 'Stock',
    'rewards.exchange': 'Exchange',
    'rewards.notEnoughPoints': 'Not Enough Points',
    'rewards.confirmExchange': 'Confirm exchange?',
    'rewards.requiredPoints': 'Required Points',
    'rewards.afterBalance': 'After Balance',
    'rewards.earned': 'Earned',
    'rewards.used': 'Used',
    'rewards.balance2': 'Balance',
    'rewards.available': 'Available',
    'rewards.usedComplete': 'Used',
    'rewards.use': 'Use',
    'rewards.noCoupons': 'No coupons available',
    
    // Map
    'map.title': 'Collection Point Map',
    'map.findLocation': 'Find My Location',
    'map.nearbyBins': 'Nearby Bins',
    'map.campaigns': 'Local Eco Campaigns',
    'map.detail': 'Collection Point Details',
    'map.operatingHours': 'Operating Hours',
    'map.acceptedItems': 'Accepted Items',
    'map.getDirections': 'Get Directions',
    'map.type.recycle': 'Recycling',
    'map.type.battery': 'Battery',
    'map.type.glass': 'Glass',
    'map.type.general': 'General',
    
    // Items
    'item.plasticBottle': 'Plastic Bottle',
    'item.foodWaste': 'Food Waste',
    'item.battery': 'Waste Battery',
    'item.paperCup': 'Paper Cup',
    'item.styrofoam': 'Styrofoam',
    'item.plasticBag': 'Plastic Bag',
    
    // Locations (Dalat)
    'location.dalat1': 'Dalat Recycling Center',
    'location.dalat2': 'Xuan Huong Battery Collection',
    'location.dalat3': 'Dalat General Collection Center',
    'location.dalat4': 'Glass Bottle Collection Point',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.1.title': '🎉 7-Day Streak!',
    'notifications.1.message': 'You have recycled for 7 consecutive days. Keep it up!',
    'notifications.2.title': '🎁 New Reward',
    'notifications.2.message': 'You can redeem Coffee Voucher with 4500 points',
    'notifications.3.title': '💡 Tip of the Day',
    'notifications.3.message': 'Rinse plastic bottles before putting them in the recycling bin',
  },
  
  vi: {
    // Common
    'common.points': 'Điểm',
    'common.kg': 'kg',
    'common.confirm': 'Xác nhận',
    'common.cancel': 'Hủy',
    'common.close': 'Đóng',
    'common.search': 'Tìm kiếm',
    'common.all': 'Tất cả',
    
    // Bottom Nav
    'nav.home': 'Trang chủ',
    'nav.camera': 'Camera',
    'nav.search': 'Tìm kiếm',
    'nav.ranking': 'Xếp hạng',
    'nav.rewards': 'Phần thưởng',
    'nav.map': 'Bản đồ',
    
    // Dashboard
    'dashboard.greeting': 'Xin chào!',
    'dashboard.username': 'Chiến binh Xanh 🌱',
    'dashboard.myPoints': 'Điểm của tôi',
    'dashboard.monthlyTotal': 'Tổng tháng này',
    'dashboard.goalProgress': 'Tiến độ mục tiêu tháng',
    'dashboard.current': 'Hiện tại',
    'dashboard.goal': 'Mục tiêu',
    'dashboard.weeklyTrend': 'Phân loại 7 ngày qua',
    'dashboard.thisWeek': 'Tuần này',
    'dashboard.lastWeek': 'Tuần trước',
    'dashboard.recycled': 'Đã tái chế',
    'dashboard.chartDescription': 'Biểu đồ số kg bạn đã phân loại trong 7 ngày',
    'dashboard.cameraRecognition': 'Nhận diện Camera',
    'dashboard.startRecycling': 'Bắt đầu phân loại',
    'dashboard.searchByName': 'Tìm theo tên',
    'dashboard.findItems': 'Tìm vật phẩm',
    'dashboard.dailyTip': '💡 Mẹo môi trường hôm nay',
    'dashboard.recentActivity': 'Hoạt động gần đây',
    'dashboard.tip1': '🌍 Tái chế 1kg nhựa giảm 2.3kg CO₂!',
    'dashboard.tip2': '♻️ Tái chế lon giúp tiết kiệm 95% năng lượng!',
    'dashboard.tip3': '💚 Một bước tuyệt vời cho hành tinh!',
    
    // Camera
    'camera.title': 'Nhận diện AI phân loại rác',
    'camera.instruction': 'Đặt vật phẩm tái chế\nvào giữa màn hình',
    'camera.result': 'Kết quả phân loại',
    'camera.category.recycle': 'Tái chế',
    'camera.category.organic': 'Hữu cơ',
    'camera.category.hazardous': 'Nguy hiểm',
    'camera.category.other': 'Khác',
    'camera.accuracy': 'Độ chính xác',
    'camera.expectedPoints': 'Điểm dự kiến',
    'camera.co2Reduction': 'Giảm CO₂',
    'camera.howTo': 'Phương pháp xử lý đúng',
    'camera.complete': 'Hoàn thành',
    'camera.weightInput': 'Nhập trọng lượng',
    'camera.enterWeight': 'Vui lòng nhập trọng lượng đã phân loại',
    'camera.earnPoints': 'Tích điểm',
    'camera.success': 'Tích điểm thành công!',
    'camera.greatChoice': 'Lựa chọn tuyệt vời cho Trái đất!',
    'camera.loadingCamera': 'Đang khởi động camera...',
    'camera.takePhoto': 'Chụp ảnh để phân tích',
    'camera.pressBelow': 'Nhấn nút bên dưới để mở camera',
    'camera.placeItem': 'Đưa vật phẩm vào khung hình',
    'camera.analyzing': 'Đang phân tích bằng AI...',
    'camera.pointsEarned': 'Điểm nhận được',
    'camera.co2Saved': 'CO₂ giảm',
    'camera.errorAnalysis': 'Lỗi phân tích',
    'camera.tryAgain': 'Thử lại',
    'camera.tryAgainDesc': 'Vui lòng chụp ảnh khác hoặc kiểm tra kết nối mạng',
    'camera.cannotConnect': 'Không thể kết nối tới AI. Vui lòng thử lại.',
    'camera.unknown': 'Không xác định',
    
    // Encyclopedia
    'encyclopedia.title': 'Bách khoa phân loại rác',
    'encyclopedia.searchPlaceholder': 'Tìm kiếm vật phẩm',
    'encyclopedia.category.recycle': 'Tái chế',
    'encyclopedia.category.organic': 'Hữu cơ',
    'encyclopedia.category.hazardous': 'Nguy hiểm',
    'encyclopedia.category.other': 'Khác',
    'encyclopedia.noResults': 'Không tìm thấy kết quả',
    'encyclopedia.detail': 'Chi tiết vật phẩm',
    'encyclopedia.disposalLocation': 'Địa điểm xử lý',
    'encyclopedia.classificationReason': 'Lý do phân loại',
    'encyclopedia.environmentalBenefit': '🌍 Lợi ích môi trường',
    'encyclopedia.processingMethod': 'Phương pháp xử lý',
    
    // Ranking
    'ranking.title': 'Bảng xếp hạng',
    'ranking.individual': 'Cá nhân',
    'ranking.class': 'Lớp học',
    'ranking.neighborhood': 'Phường',
    'ranking.weekly': 'Tuần',
    'ranking.monthly': 'Tháng',
    'ranking.you': 'Bạn',
    'ranking.members': 'thành viên',
    'ranking.badges': 'Bộ sưu tập huy hiệu',
    'ranking.yourRank': 'Hạng của bạn',
    'ranking.points': 'Điểm',
    'ranking.streak': 'Streak',
    'ranking.viewMyPosition': 'Xem vị trí của tôi',
    'ranking.vsLastWeek': 'so với tuần trước',
    'ranking.badge.streak7': 'Tham gia 7 ngày liên tiếp',
    'ranking.badge.kg100': 'Đạt 100kg',
    'ranking.badge.master': 'Bậc thầy Xanh',
    'ranking.badge.points1000': '1000 Điểm',
    'ranking.badge.streak30': 'Tham gia 30 ngày liên tiếp',
    'ranking.allTime': 'Tất cả',
    'ranking.badge.description.streak7': 'Phân loại rác 7 ngày liên tiếp',
    'ranking.badge.description.kg100': 'Tổng cộng phân loại được 100kg rác',
    'ranking.badge.description.master': 'Đạt cấp độ Eco Master',
    'ranking.badge.description.points1000': 'Tích lũy được 1000 điểm thưởng',
    'ranking.badge.description.streak30': 'Phân loại rác 30 ngày liên tiếp',
    'ranking.badge.condition.streak7': 'Streak >= 7 ngày',
    'ranking.badge.condition.kg100': 'Tổng kg >= 100',
    'ranking.badge.condition.master': 'Hoàn thành 50 lần phân loại',
    'ranking.badge.condition.points1000': 'Điểm >= 1000',
    'ranking.badge.condition.streak30': 'Streak >= 30 ngày',
    'ranking.progress': 'Tiến độ',
    'ranking.unlocked': 'Đã mở khóa',
    'ranking.locked': 'Chưa mở',
    'ranking.badgeDetail': 'Chi tiết huy hiệu',
    
    // Rewards Extended
    'rewards.featured': 'Sản phẩm nổi bật',
    'rewards.hot': 'HOT',
    'rewards.pointsNeeded': 'Còn thiếu',
    'rewards.default': 'Mặc định',
    'rewards.priceLow': 'Giá thấp',
    'rewards.priceHigh': 'Giá cao',
    'rewards.showQR': 'Hiển thị QR',
    'rewards.couponCode': 'Mã coupon',
    'rewards.expiresIn': 'Hết hạn sau',
    'rewards.days': 'ngày',
    'rewards.expired': 'Đã hết hạn',
    'rewards.expiringSoon': 'Sắp hết hạn',
    'rewards.noHistory': 'Chưa có lịch sử',
    'rewards.nextReward': 'Phần thưởng tiếp theo',
    'rewards.progressToNext': 'Tiến độ đến phần thưởng kế tiếp',
    
    // Map Extended
    'map.searchPlaceholder': 'Tìm kiếm địa điểm, vật liệu...',
    'map.updateLocation': 'Cập nhật vị trí',
    'map.sortBy': 'Sắp xếp',
    'map.sortDistance': 'Gần nhất',
    'map.sortName': 'Tên A-Z',
    'map.favorites': 'yêu thích',
    'map.noResults': 'Không tìm thấy địa điểm',
    'map.clearFilter': 'Xóa bộ lọc',
    'map.points': 'điểm',
    'map.events': 'sự kiện',
    'map.participants': 'người',
    'map.registered': 'Đã đăng ký',
    'map.register': 'Đăng ký tham gia',
    'map.full': 'Đã đủ người',
    'map.cancelRegistration': 'Đã hủy đăng ký',
    'map.registerSuccess': 'Đăng ký thành công!',
    'map.share': 'Chia sẻ',
    'map.linkCopied': 'Đã sao chép link!',
    'map.favorite': 'Yêu thích',
    'map.coordinates': 'Tọa độ',
    'map.shareLocation': 'Chia sẻ địa điểm',
    'map.gpsError.denied': 'Bạn đã từ chối quyền truy cập vị trí',
    'map.gpsError.unavailable': 'Không thể xác định vị trí',
    'map.gpsError.timeout': 'Quá thời gian chờ',
    'map.gpsError.unknown': 'Lỗi không xác định',
    'map.gpsError.noSupport': 'Trình duyệt không hỗ trợ GPS',
    
    // Encyclopedia Extended
    'encyclopedia.aiSearch': 'Tìm kiếm AI',
    'encyclopedia.searching': 'Đang tìm kiếm...',
    'encyclopedia.searchHistory': 'Lịch sử tìm kiếm',
    'encyclopedia.clearHistory': 'Xóa lịch sử',
    'encyclopedia.popularSearches': 'Tìm kiếm phổ biến',
    'encyclopedia.aiResult': 'Kết quả AI',
    'encyclopedia.searchError': 'Không thể tìm kiếm. Vui lòng thử lại.',
    
    // Campaign
    'campaign.title1': 'Chiến dịch Môi trường Đà Lạt',
    'campaign.desc1': 'Thử thách Không Nhựa',
    'campaign.title2': 'Chương trình Giáo dục Tái chế',
    'campaign.desc2': 'Phương pháp phân loại đúng',
    'campaign.title3': 'Dọn dẹp Hồ Tuyền Lâm',
    'campaign.desc3': 'Thu gom rác quanh hồ',
    
    // Rewards
    'rewards.title': 'Cửa hàng phần thưởng',
    'rewards.balance': 'Số dư điểm',
    'rewards.shop': 'Cửa hàng',
    'rewards.history': 'Lịch sử điểm',
    'rewards.myCoupons': 'Phiếu của tôi',
    'rewards.category.coupons': 'Phiếu',
    'rewards.category.ecoGoods': 'Đồ xanh',
    'rewards.category.certificate': 'Chứng chỉ điện tử',
    'rewards.stock': 'Tồn kho',
    'rewards.exchange': 'Đổi',
    'rewards.notEnoughPoints': 'Không đủ điểm',
    'rewards.confirmExchange': 'Xác nhận đổi?',
    'rewards.requiredPoints': 'Điểm yêu cầu',
    'rewards.afterBalance': 'Số dư sau',
    'rewards.earned': 'Tích',
    'rewards.used': 'Dùng',
    'rewards.balance2': 'Số dư',
    'rewards.available': 'Có thể dùng',
    'rewards.usedComplete': 'Đã dùng',
    'rewards.use': 'Sử dụng',
    'rewards.noCoupons': 'Không có phiếu nào',
    
    // Map
    'map.title': 'Bản đồ điểm thu gom',
    'map.findLocation': 'Tìm vị trí của tôi',
    'map.nearbyBins': 'Thùng rác gần đây',
    'map.campaigns': 'Chiến dịch môi trường địa phương',
    'map.detail': 'Chi tiết điểm thu gom',
    'map.operatingHours': 'Giờ hoạt động',
    'map.acceptedItems': 'Vật phẩm chấp nhận',
    'map.getDirections': 'Chỉ đường',
    'map.type.recycle': 'Tái chế',
    'map.type.battery': 'Pin',
    'map.type.glass': 'Thủy tinh',
    'map.type.general': 'Chung',
    
    // Items
    'item.plasticBottle': 'Chai nhựa',
    'item.foodWaste': 'Rác thực phẩm',
    'item.battery': 'Pin thải',
    'item.paperCup': 'Cốc giấy',
    'item.styrofoam': 'Xốp',
    'item.plasticBag': 'Túi nilon',
    
    // Locations (Dalat)
    'location.dalat1': 'Trung tâm Tái chế Đà Lạt',
    'location.dalat2': 'Thu gom Pin Xuân Hương',
    'location.dalat3': 'Trung tâm Thu gom Tổng hợp Đà Lạt',
    'location.dalat4': 'Điểm Thu gom Chai Thủy tinh',
    
    // Notifications
    'notifications.title': 'Thông báo',
    'notifications.1.title': '🎉 Streak 7 ngày!',
    'notifications.1.message': 'Bạn đã tái chế 7 ngày liên tiếp. Tiếp tục phát huy!',
    'notifications.2.title': '🎁 Phần thưởng mới',
    'notifications.2.message': 'Bạn có thể đổi Coffee Voucher với 4500 điểm',
    'notifications.3.title': '💡 Mẹo hôm nay',
    'notifications.3.message': 'Rửa sạch chai nhựa trước khi bỏ vào thùng tái chế',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Initialize from localStorage
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored && (stored === 'vi' || stored === 'en' || stored === 'ko')) {
      return stored as Language;
    }
    return 'vi'; // Default to Vietnamese for Dalat
  });

  // Sync to localStorage whenever language changes
  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['vi']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
